Fix fastboot support
kellyselden/ember-router-service pull request #11
Opened 2016-11-23 21:14 UTC by trabus

When using fastboot, the router service is only present for the first request, and afterwards is `undefined`.

Instead of returning early, we should use `appInstance.register` for Ember 2.x, use `appInstance.application.register` for Ember 1.13.

2016-11-23 21:23 UTC, kellyselden commented
Can I get a test for this please?

2016-11-23 23:53 UTC, kellyselden commented on addon/instance-initializers/router-service.js
> +    appInstance.register(fullName, router, { singleton: true, instantiate: false });
can you not duplicate code, create a `registerSource` var.

2016-11-23 23:55 UTC, kellyselden commented on tests/unit/instance-initializers/router-service-test.js
> +  assert.ok(register.calledOnce);
how do you know which register got called, `appInstance.register` or `appInstance.application.register`?

2016-11-23 23:55 UTC, kellyselden requested changes
registerSource var

2016-11-24 00:58 UTC, trabus reviewed
👍

2016-11-24 01:20 UTC, kellyselden commented on tests/unit/instance-initializers/router-service-test.js
> +  if (this.appInstance.hasRegistration) {
remove block

2016-11-24 01:21 UTC, kellyselden commented on tests/unit/instance-initializers/router-service-test.js
> +  if (!this.appInstance.hasRegistration) {
remove block

2016-11-24 01:27 UTC, kellyselden approved these changes

2016-11-24 01:29 UTC, merged